package com.TTT.Debug

enum class TraceEventType {
    // Existing Pipe Events
    PIPE_START,
    PIPE_END,
    PIPE_SUCCESS,
    PIPE_FAILURE,
    CONTEXT_PULL,
    CONTEXT_TRUNCATE,
    PRE_INVOKE,
    VALIDATION_START,
    VALIDATION_SUCCESS,
    VALIDATION_FAILURE,
    TRANSFORMATION_START,
    TRANSFORMATION_SUCCESS,
    TRANSFORMATION_FAILURE,
    API_CALL_START,
    API_CALL_SUCCESS,
    API_CALL_FAILURE,
    BRANCH_PIPE_TRIGGERED,
    PIPELINE_TERMINATION,
    
    // Manifold Orchestration Events
    MANIFOLD_START,
    MANIFOLD_END,
    MANIFOLD_SUCCESS,
    MANIFOLD_FAILURE,
    
    // Manager Decision Events
    MANAGER_DECISION,
    MANAGER_TASK_ANALYSIS,
    MANAGER_AGENT_SELECTION,
    
    // Task Progress Events
    TASK_PROGRESS_UPDATE,
    TASK_COMPLETION_CHECK,
    TASK_NEXT_STEPS,
    
    // Agent Communication Events
    AGENT_DISPATCH,
    AGENT_RESPONSE,
    AGENT_REQUEST_VALIDATION,
    AGENT_RESPONSE_PROCESSING,
    
    // P2P Communication Events
    P2P_REQUEST_START,
    P2P_REQUEST_SUCCESS,
    P2P_REQUEST_FAILURE,
    P2P_TRANSPORT_SEND,
    P2P_TRANSPORT_RECEIVE,
    PCP_CONTEXT_TRANSFER,
    
    // Loop and Control Events
    MANIFOLD_LOOP_ITERATION,
    MANIFOLD_TERMINATION_CHECK,
    CONVERSE_HISTORY_UPDATE,
    
    // Error and Recovery Events
    AGENT_REQUEST_INVALID,
    P2P_COMMUNICATION_FAILURE,
    MANIFOLD_RECOVERY_ATTEMPT,
    
    // Splitter Orchestration Events
    SPLITTER_START,
    SPLITTER_END,
    SPLITTER_SUCCESS,
    SPLITTER_FAILURE,
    
    // Content Distribution Events  
    SPLITTER_CONTENT_DISTRIBUTION,
    SPLITTER_PIPELINE_DISPATCH,
    SPLITTER_PIPELINE_COMPLETION,
    
    // Callback Events
    SPLITTER_PIPELINE_CALLBACK,
    SPLITTER_COMPLETION_CALLBACK,
    
    // Parallel Execution Events
    SPLITTER_PARALLEL_START,
    SPLITTER_PARALLEL_AWAIT,
    SPLITTER_RESULT_COLLECTION
}