kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2g

#=========================================Maven Central Publishing Secrets=========================================
# SIGNING_KEY         - GPG private key (armored ASCII, base64 encoded)
# SIGNING_PASSWORD     - GPG key passphrase
# OSSRH_USERNAME      - Sonatype OSSRH username
# OSSRH_PASSWORD      - Sonatype OSSRH password
