#!/bin/bash
awk '
/fun clearGuardrail/ {
    print $0
    in_func = 1
    next
}
in_func && /^    \}/ {
    print $0
    print ""
    print "    /**"
    print "     * Evaluates content against the configured guardrail without invoking foundation models."
    print "     * This allows independent content validation at any stage of your application flow."
    print "     * "
    print "     * @param content The text content to evaluate"
    print "     * @param source Whether content is from user input (\"INPUT\") or model output (\"OUTPUT\")"
    print "     * @param fullOutput Return full assessment including non-detected content for debugging"
    print "     * @return ApplyGuardrailResponse containing action taken and detailed assessments"
    print "     * "
    print "     * @throws IllegalStateException if guardrail is not configured"
    print "     * @throws IllegalArgumentException if client is not initialized"
    print "     * "
    print "     * @see setGuardrail to configure guardrail before calling this method"
    print "     * "
    print "     * @since Requires bedrock:ApplyGuardrail IAM permission"
    print "     */"
    print "    suspend fun applyGuardrailStandalone("
    print "        content: String,"
    print "        source: String = \"INPUT\","
    print "        fullOutput: Boolean = false"
    print "    ): ApplyGuardrailResponse? {"
    print "        // Validate guardrail configuration"
    print "        if (guardrailIdentifier.isEmpty()) {"
    print "            trace(TraceEventType.API_CALL_FAILURE, TracePhase.EXECUTION,"
    print "                  metadata = mapOf(\"error\" to \"Guardrail not configured\"))"
    print "            throw IllegalStateException(\"Guardrail must be configured before calling applyGuardrailStandalone. Use setGuardrail() first.\")"
    print "        }"
    print "        "
    print "        // Validate client initialization"
    print "        val client = bedrockClient ?: run {"
    print "            trace(TraceEventType.API_CALL_FAILURE, TracePhase.EXECUTION,"
    print "                  metadata = mapOf(\"error\" to \"Client not initialized\"))"
    print "            throw IllegalArgumentException(\"BedrockPipe must be initialized before applying guardrails. Call init() first.\")"
    print "        }"
    print "        "
    print "        trace(TraceEventType.API_CALL_START, TracePhase.EXECUTION,"
    print "              metadata = mapOf("
    print "                  \"method\" to \"applyGuardrailStandalone\","
    print "                  \"guardrailId\" to guardrailIdentifier,"
    print "                  \"guardrailVersion\" to guardrailVersion,"
    print "                  \"source\" to source,"
    print "                  \"contentLength\" to content.length,"
    print "                  \"fullOutput\" to fullOutput"
    print "              ))"
    print "        "
    print "        return try {"
    print "            val request = ApplyGuardrailRequest {"
    print "                this.guardrailIdentifier = this@BedrockPipe.guardrailIdentifier"
    print "                this.guardrailVersion = this@BedrockPipe.guardrailVersion"
    print "                this.source = GuardrailContentSource.fromValue(source)"
    print "                this.content = listOf("
    print "                    GuardrailContentBlock.Text("
    print "                        GuardrailTextBlock {"
    print "                            this.text = content"
    print "                        }"
    print "                    )"
    print "                )"
    print "            }"
    print "            "
    print "            val response = client.applyGuardrail(request)"
    print "            "
    print "            trace(TraceEventType.API_CALL_SUCCESS, TracePhase.EXECUTION,"
    print "                  metadata = mapOf("
    print "                      \"action\" to response.action.toString(),"
    print "                      \"outputCount\" to response.outputs?.size,"
    print "                      \"hasAssessments\" to (response.assessments?.isNotEmpty() ?: false)"
    print "                  ))"
    print "            "
    print "            response"
    print "            "
    print "        } catch (e: Exception) {"
    print "            trace(TraceEventType.API_CALL_FAILURE, TracePhase.EXECUTION,"
    print "                  metadata = mapOf(\"error\" to e.message), error = e)"
    print "            null"
    print "        }"
    print "    }"
    in_func = 0
    next
}
{ print }
' TPipe-Bedrock/src/main/kotlin/bedrockPipe/BedrockPipe.kt > TPipe-Bedrock/src/main/kotlin/bedrockPipe/BedrockPipe.kt.new
mv TPipe-Bedrock/src/main/kotlin/bedrockPipe/BedrockPipe.kt.new TPipe-Bedrock/src/main/kotlin/bedrockPipe/BedrockPipe.kt
