#!/bin/bash
awk '
/fun setServiceTier/ {
    print "    /**"
    print "     * Sets the guardrail to use for content filtering and safety policies."
    print "     * Guardrails evaluate both user inputs and model responses against configured policies"
    print "     * including content filters, denied topics, sensitive information filters, and word filters."
    print "     * "
    print "     * @param identifier The guardrail identifier (ID or ARN)"
    print "     * @param version The guardrail version to use (version number or \"DRAFT\")"
    print "     * @param enableTrace Enable guardrail tracing for debugging (default: false)"
    print "     * @return This BedrockPipe instance for method chaining"
    print "     * "
    print "     * @see clearGuardrail to remove guardrail configuration"
    print "     * @see applyGuardrailStandalone for standalone content evaluation"
    print "     * "
    print "     * @since Requires bedrock:ApplyGuardrail IAM permission"
    print "     */"
    print "    fun setGuardrail(identifier: String, version: String = \"DRAFT\", enableTrace: Boolean = false): BedrockPipe {"
    print "        this.guardrailIdentifier = identifier"
    print "        this.guardrailVersion = version"
    print "        this.guardrailTrace = if (enableTrace) \"enabled\" else \"disabled\""
    print "        return this"
    print "    }"
    print ""
    print "    /**"
    print "     * Enables full guardrail tracing which includes both detected and non-detected content"
    print "     * for enhanced debugging. Only applies to content filters, denied topics, sensitive"
    print "     * information PII detection, and contextual grounding policies."
    print "     * "
    print "     * @return This BedrockPipe instance for method chaining"
    print "     */"
    print "    fun enableFullGuardrailTrace(): BedrockPipe {"
    print "        this.guardrailTrace = \"enabled_full\""
    print "        return this"
    print "    }"
    print ""
    print "    /**"
    print "     * Clears the guardrail configuration, disabling content filtering."
    print "     * "
    print "     * @return This BedrockPipe instance for method chaining"
    print "     */"
    print "    fun clearGuardrail(): BedrockPipe {"
    print "        this.guardrailIdentifier = \"\""
    print "        this.guardrailVersion = \"\""
    print "        this.guardrailTrace = \"disabled\""
    print "        return this"
    print "    }"
    print ""
    print $0
    next
}
{ print }
' TPipe-Bedrock/src/main/kotlin/bedrockPipe/BedrockPipe.kt > TPipe-Bedrock/src/main/kotlin/bedrockPipe/BedrockPipe.kt.new
mv TPipe-Bedrock/src/main/kotlin/bedrockPipe/BedrockPipe.kt.new TPipe-Bedrock/src/main/kotlin/bedrockPipe/BedrockPipe.kt
