package genericOpenAIPipe.mantle

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Unit tests for [ChunkedSigV4Signer]. The principal tests pin the signer
 * against authoritative reference values generated by a hand-written Go
 * signer following the AWS-documented chunked-streaming algorithm
 * (`docs.aws.amazon.com/AmazonS3/latest/developerguide/sigv4-streaming.html`).
 *
 * Reference vectors generated on 2026-07-29 with the canonical algorithm:
 *   - access key: `AKIDEXAMPLE`
 *   - secret: `wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY`
 *   - region: `us-east-1`
 *   - service: `bedrock-mantle`
 *   - timestamp: `20150830T123600Z`
 *   - credential scope: `20150830/us-east-1/bedrock-mantle/aws4_request`
 *   - seed signature: 64 zeros (placeholder)
 */
class ChunkedSigV4SignerTest
{

    //================================================AwsAlgorithmReference================================================

    /**
     * Pins the chunked signer against an authoritative Go reference for the
     * canonical AWS S3 streaming algorithm with Mantle-shaped service.
     *
     * Reference values generated on 2026-07-29 by a hand-written Go signer
     * implementing the AWS-documented chain.
     */
    @Test
    fun testFirstChunkMatchesAwsAlgorithmReference()
    {
        val fixedEpoch: Clock = Clock { 1440938160000L }
        val signer = ChunkedSigV4Signer(
            accessKeyId = "AKIDEXAMPLE",
            secretAccessKey = "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY",
            region = "us-east-1",
            service = "bedrock-mantle",
            clock = fixedEpoch,
        )
        val seedSignature = "0".repeat(64)
        val chunk1 = ByteArray(ChunkedSigV4Signer.CHUNK_SIZE_BYTES) { 'a'.code.toByte() }
        val result = signer.signChunk(seedSignature, chunk1)

        assertEquals(
            "db3c2a5a66c4f43002800267d1b03b8644a5a96d6996343f088fb3bcea31755a",
            result.signatureHex,
            "Chunk 1 signature must match the AWS algorithm reference"
        )
        // nextSeedSha256Hex is sha256(signatureHex) — SHA256 of the
        // 64-char lowercase-hex string.
        assertEquals(64, result.nextSeedSha256Hex.length)
        assertTrue(result.nextSeedSha256Hex.all { it in '0'..'9' || it in 'a'..'f' })
    }

    /**
     * Pins a two-chunk chain. Chunk 2's `previousSignature` is chunk 1's
     * signature, NOT the seed. The chain propagation is the whole point
     * of chunked SigV4.
     */
    @Test
    fun testTwoChunkChainMatchesReference()
    {
        val fixedEpoch: Clock = Clock { 1440938160000L }
        val signer = ChunkedSigV4Signer(
            accessKeyId = "AKIDEXAMPLE",
            secretAccessKey = "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY",
            region = "us-east-1",
            service = "bedrock-mantle",
            clock = fixedEpoch,
        )
        val seedSignature = "0".repeat(64)
        val chunk1 = ByteArray(ChunkedSigV4Signer.CHUNK_SIZE_BYTES) { 'a'.code.toByte() }
        val result1 = signer.signChunk(seedSignature, chunk1)

        // Chunk 2: 1 byte 'b'. Uses chunk 1's signature as previous.
        val chunk2 = byteArrayOf('b'.code.toByte())
        val result2 = signer.signChunk(result1.signatureHex, chunk2)

        assertEquals(
            "a6e985013437298ecc256207d56795e96819ace64886849d7931c28e625e4355",
            result2.signatureHex,
            "Chunk 2 signature must match the AWS algorithm reference (chained from chunk 1)"
        )
    }

    /**
     * Pins the 0-byte terminator chunk. The body hash is the empty-payload
     * SHA256, and the terminator signature closes the chain.
     */
    @Test
    fun testEmptyTerminatorChunkMatchesReference()
    {
        val fixedEpoch: Clock = Clock { 1440938160000L }
        val signer = ChunkedSigV4Signer(
            accessKeyId = "AKIDEXAMPLE",
            secretAccessKey = "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY",
            region = "us-east-1",
            service = "bedrock-mantle",
            clock = fixedEpoch,
        )
        val seedSignature = "0".repeat(64)
        // Use chunk 2's signature from the reference as the previous.
        val chunk2Sig = "a6e985013437298ecc256207d56795e96819ace64886849d7931c28e625e4355"

        val result = signer.signChunk(chunk2Sig, ByteArray(0))
        assertEquals(
            "fec1846f59fa22daaac4a58e17780ce6e90a4ee494578a82616af0373e3f0eb9",
            result.signatureHex,
            "Empty terminator signature must match the AWS algorithm reference"
        )
    }

    //================================================ByteStability================================================

    /**
     * Two invocations with the same inputs and the same clock produce
     * byte-identical signatures. Critical for streaming replay and
     * reproducibility.
     */
    @Test
    fun testSignatureStableAcrossCalls()
    {
        val fixedEpoch: Clock = Clock { 1440938160000L }
        val signer = ChunkedSigV4Signer(
            accessKeyId = "AKIDEXAMPLE",
            secretAccessKey = "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY",
            region = "us-east-1",
            service = "bedrock-mantle",
            clock = fixedEpoch,
        )
        val seed = "0".repeat(64)
        val chunk = "hello".toByteArray()
        val r1 = signer.signChunk(seed, chunk)
        val r2 = signer.signChunk(seed, chunk)
        assertEquals(r1.signatureHex, r2.signatureHex)
        assertEquals(r1.nextSeedSha256Hex, r2.nextSeedSha256Hex)
    }

    /**
     * Different chunk bytes produce different signatures (sanity check on
     * the chain propagating the chunk hash).
     */
    @Test
    fun testDifferentChunkBytesProduceDifferentSignatures()
    {
        val fixedEpoch: Clock = Clock { 1440938160000L }
        val signer = ChunkedSigV4Signer(
            accessKeyId = "AKIDEXAMPLE",
            secretAccessKey = "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY",
            region = "us-east-1",
            service = "bedrock-mantle",
            clock = fixedEpoch,
        )
        val seed = "0".repeat(64)
        val r1 = signer.signChunk(seed, "hello".toByteArray())
        val r2 = signer.signChunk(seed, "world".toByteArray())
        assertTrue(r1.signatureHex != r2.signatureHex, "Different bytes must produce different signatures")
    }

    /**
     * Different previous-signature inputs produce different signatures,
     * confirming the chain actually depends on the prior chunk signature
     * (not just the chunk bytes).
     */
    @Test
    fun testDifferentPreviousSignatureProducesDifferentSignatures()
    {
        val fixedEpoch: Clock = Clock { 1440938160000L }
        val signer = ChunkedSigV4Signer(
            accessKeyId = "AKIDEXAMPLE",
            secretAccessKey = "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY",
            region = "us-east-1",
            service = "bedrock-mantle",
            clock = fixedEpoch,
        )
        val chunk = "hello".toByteArray()
        val r1 = signer.signChunk("0".repeat(64), chunk)
        val r2 = signer.signChunk("1".repeat(64), chunk)
        assertTrue(r1.signatureHex != r2.signatureHex, "Different previous signatures must produce different signatures")
    }

    //================================================Validation================================================

    @Test
    fun testBlankPreviousSignatureRejected()
    {
        val signer = ChunkedSigV4Signer(
            accessKeyId = "AKID",
            secretAccessKey = "SECRET",
            region = "us-east-1",
        )
        try
        {
            signer.signChunk("", ByteArray(0))
            kotlin.test.fail("Expected IllegalArgumentException for blank previousSignatureHex")
        }
        catch (e: IllegalArgumentException)
        {
            // expected
        }
    }

    @Test
    fun testBlankAccessKeyIdRejected()
    {
        try
        {
            ChunkedSigV4Signer(
                accessKeyId = "",
                secretAccessKey = "SECRET",
                region = "us-east-1",
            )
            kotlin.test.fail("Expected IllegalArgumentException for blank accessKeyId")
        }
        catch (e: IllegalArgumentException)
        {
            // expected
        }
    }

    @Test
    fun testBlankRegionRejected()
    {
        try
        {
            ChunkedSigV4Signer(
                accessKeyId = "AKID",
                secretAccessKey = "SECRET",
                region = "",
            )
            kotlin.test.fail("Expected IllegalArgumentException for blank region")
        }
        catch (e: IllegalArgumentException)
        {
            // expected
        }
    }

    //================================================Constants================================================

    @Test
    fun testStreamingContentSha256ConstantMatchesAwsSpec()
    {
        assertEquals(
            "STREAMING-AWS4-HMAC-SHA256-PAYLOAD",
            ChunkedSigV4Signer.STREAMING_CONTENT_SHA256
        )
    }

    @Test
    fun testChunkSizeConstantMatchesAwsRecommendation()
    {
        assertEquals(65_536, ChunkedSigV4Signer.CHUNK_SIZE_BYTES)
    }

    @Test
    fun testEmptyPayloadHashMatchesAwsSpec()
    {
        assertEquals(
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            ChunkedSigV4Signer.EMPTY_PAYLOAD_HASH
        )
    }
}