#!/usr/bin/env bash
# lldb_harness.sh
#
# Phase 7 — LLDB-backed runtime inspector for the TPipe C integration tests.
#
# This script:
#   1. Locates the native .so (or builds it via ./gradlew nativeCompile)
#   2. Compiles the requested C integration test
#   3. Runs the test under lldb --batch with breakpoints on the key
#      TPipe_Content_create / TPipe_Content_release symbols
#   4. Prints the captured LLDB session transcript
#   5. Asserts zero leaks via the test's own exit code
#
# Usage:
#     bash test/native/c/lldb_harness.sh tpipe_lifecycle_test
#     bash test/native/c/lldb_harness.sh tpipe_handle_leak_test
#     bash test/native/c/lldb_harness.sh tpipe_concurrency_test
#     bash test/native/c/lldb_harness.sh tpipe_lifecycle_test /path/to/TPipe.so
#
# If the .so path is not provided, the harness will:
#   - look for a pre-built one in ./build/native/nativeCompile/TPipe.so
#   - and if absent, run `./gradlew nativeCompile` to build it.
#
# Environment variables (all optional):
#     TPIPE_LIB   override the path to the TPipe .so
#     SKIP_BUILD  set to 1 to skip the gradle build even when .so is missing
#     KEEP_BUILD  set to 1 to leave the compiled test binary on disk
#
# Exit codes:
#     0   the C test passed AND LLDB session was clean
#     1   the C test failed (LLDB exit != 0, or test's exit code non-zero)
#     2   setup error (bad test name, no lldb, no .so, no gcc)
#     3   gradle build failed

set -uo pipefail

#==============================================================================
# Paths
#==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# SCRIPT_DIR is .../<project>/test/native/c, so 3 levels up is the project root.
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
GRADLEW="$PROJECT_ROOT/gradlew"
ABI_HEADER_DIR="$PROJECT_ROOT/src/main/resources"
NATIVE_COMPILE_DIR="$PROJECT_ROOT/build/native/nativeCompile"

#==============================================================================
# Argument parsing
#==============================================================================

TEST_NAME="${1:-}"
TPIPE_LIB="${2:-${TPIPE_LIB:-}}"

if [ -z "$TEST_NAME" ]; then
    echo "Usage: $0 <test_basename_no_ext> [/path/to/TPipe.so]" >&2
    echo "  available tests: tpipe_lifecycle_test, tpipe_handle_leak_test, tpipe_concurrency_test" >&2
    exit 2
fi

TEST_C="$SCRIPT_DIR/${TEST_NAME}.c"
if [ ! -f "$TEST_C" ]; then
    echo "ERROR: test source not found: $TEST_C" >&2
    exit 2
fi

#==============================================================================
# Tool checks
#==============================================================================

if ! command -v lldb >/dev/null 2>&1; then
    echo "ERROR: lldb not found in PATH" >&2
    exit 2
fi
if ! command -v gcc >/dev/null 2>&1; then
    echo "ERROR: gcc not found in PATH" >&2
    exit 2
fi

#==============================================================================
# Locate (or build) the TPipe .so
#==============================================================================

if [ -z "$TPIPE_LIB" ] || [ ! -f "$TPIPE_LIB" ]; then
    for candidate in \
        "$NATIVE_COMPILE_DIR/TPipe.so" \
        "$NATIVE_COMPILE_DIR/TPipe.dylib" \
        "$NATIVE_COMPILE_DIR/TPipe.dll"; do
        if [ -f "$candidate" ]; then
            TPIPE_LIB="$candidate"
            break
        fi
    done
fi

if [ -z "$TPIPE_LIB" ] || [ ! -f "$TPIPE_LIB" ]; then
    if [ "${SKIP_BUILD:-0}" = "1" ]; then
        echo "ERROR: TPipe .so not found and SKIP_BUILD=1" >&2
        exit 2
    fi
    if [ ! -x "$GRADLEW" ]; then
        echo "ERROR: TPipe .so not found and gradlew not executable at $GRADLEW" >&2
        exit 2
    fi
    echo "==> Building native .so via $GRADLEW nativeCompile (this may take a few minutes)..."
    (cd "$PROJECT_ROOT" && "$GRADLEW" nativeCompile) || {
        echo "ERROR: gradle nativeCompile failed" >&2
        exit 3
    }
    # Re-locate
    for candidate in \
        "$NATIVE_COMPILE_DIR/TPipe.so" \
        "$NATIVE_COMPILE_DIR/TPipe.dylib" \
        "$NATIVE_COMPILE_DIR/TPipe.dll"; do
        if [ -f "$candidate" ]; then
            TPIPE_LIB="$candidate"
            break
        fi
    done
    if [ -z "$TPIPE_LIB" ] || [ ! -f "$TPIPE_LIB" ]; then
        echo "ERROR: build did not produce a .so" >&2
        exit 3
    fi
fi

echo "==> Using TPipe library: $TPIPE_LIB"

#==============================================================================
# Locate graal_isolate.h (the SDK header that defines the IsolateThread
# structs). It is generated by native-image alongside the .so.
#==============================================================================

ISO_INCLUDE_DIR=""
if [ -f "$NATIVE_COMPILE_DIR/graal_isolate.h" ]; then
    ISO_INCLUDE_DIR="$NATIVE_COMPILE_DIR"
fi

#==============================================================================
# Compile the C test
#==============================================================================

TEST_BIN="$SCRIPT_DIR/${TEST_NAME}.lldb_bin"
LINK_FLAGS="-ldl"
if [[ "$TEST_NAME" == *concurrency* ]]; then
    LINK_FLAGS="-ldl -lpthread"
fi

echo "==> Compiling $TEST_C -> $TEST_BIN"
if [ -n "$ISO_INCLUDE_DIR" ]; then
    gcc -O0 -g -o "$TEST_BIN" "$TEST_C" $LINK_FLAGS \
        -I"$ISO_INCLUDE_DIR" -I"$ABI_HEADER_DIR" || {
        echo "ERROR: gcc failed" >&2
        exit 2
    }
else
    gcc -O0 -g -o "$TEST_BIN" "$TEST_C" $LINK_FLAGS \
        -I"$ABI_HEADER_DIR" || {
        echo "ERROR: gcc failed" >&2
        exit 2
    }
fi
echo "==> Compiled: $(ls -la "$TEST_BIN" | awk '{print $5}') bytes"

#==============================================================================
# Build the LLDB batch script
#==============================================================================
#
# We use `breakpoint set --name` (not `b -r`) so we can rely on LLDB's
# pending-breakpoint resolution when the .so is not yet loaded. We use
# `breakpoint command add` to print the call site frame each time a
# breakpoint is hit, which gives us a runtime trace of the C ABI surface.
#
# `process handle SIGPIPE -p true -s false -n false` and
# `process handle SIGSEGV -p true -s true -n false` let the test continue
# to print its own summary even when SubstrateVM trips its known
# safepoint abort during teardown (the test's own exit code is the
# source of truth — same pattern used in tpipe_abi_compliance.c).

LLDB_SCRIPT="$(mktemp -t lldb_harness.XXXXXX.lldb)"
# Use a single-quoted heredoc to disable bash variable substitution and
# command substitution. The few variables we need are substituted below
# via sed, so we keep the script body free of backticks and $ characters
# that would otherwise be interpreted by bash.
cat > "$LLDB_SCRIPT" <<'LLDB_EOF_BODY'
# LLDB batch script generated by lldb_harness.sh
settings set auto-confirm true

# Load the test binary
file __TEST_BIN__

# Resolve the TPipe .so early so the breakpoint names resolve on attach.
# (LLDB will accept unresolved names as pending breakpoints either way.)
settings set target.exec-search-paths "__NATIVE_COMPILE_DIR__"

# Set breakpoints on the three highest-traffic ABI symbols. These names
# resolve in the .so once the run command has loaded it. The -G true
# flag enables auto-continue, so each hit prints its trace and then
# the process keeps running without manual 'continue' commands.
breakpoint set --name TPipe_Content_create -G true
breakpoint set --name TPipe_Content_release -G true
breakpoint set --name TPipe_Handle_release -G true

# Print one frame when each breakpoint hits. The exact number of hits
# is data — it tells us the test actually exercised the function. The
# auto-continue flag above ensures the test runs to natural completion
# even when many breakpoints fire in a row.
breakpoint command add 1
thread backtrace 1
DONE
breakpoint command add 2
thread backtrace 1
DONE
breakpoint command add 3
thread backtrace 1
DONE

# Run with the .so path as argv[1]
run __TPIPE_LIB__

# The C test will reach its natural exit (or SubstrateVM's safepoint
# abort during teardown). The 'quit' command below detaches LLDB.
quit
LLDB_EOF_BODY

# Substitute the placeholders. Using sed with | delimiter so the .so
# path (which may contain a /) is not interpreted as a sed separator.
sed -i \
    -e "s|__TEST_BIN__|$TEST_BIN|g" \
    -e "s|__NATIVE_COMPILE_DIR__|$NATIVE_COMPILE_DIR|g" \
    -e "s|__TPIPE_LIB__|$TPIPE_LIB|g" \
    "$LLDB_SCRIPT"

#==============================================================================
# Run LLDB
#==============================================================================

echo "==> Running $TEST_BIN under lldb --batch"
LLDB_LOG="$SCRIPT_DIR/${TEST_NAME}.lldb_log"
echo "    (full transcript: $LLDB_LOG)"

set +e
lldb --batch -s "$LLDB_SCRIPT" 2>&1 | tee "$LLDB_LOG"
LLDB_RC=$?
set -e

#==============================================================================
# Post-run analysis
#==============================================================================

# The C test's exit code is embedded in the LLDB log — look for the
# "Process X exited with status = N" line. This is what we trust as the
# "zero leaks" assertion.

TEST_EXIT_LINE="$(grep -E 'Process [0-9]+ exited' "$LLDB_LOG" | tail -1 || true)"
if [ -n "$TEST_EXIT_LINE" ]; then
    echo "==> $TEST_EXIT_LINE"
fi

# Count how many times the breakpoints fired.
HITS_CREATE="$(grep -cE 'stop reason = breakpoint 1\.[0-9]+' "$LLDB_LOG" || true)"
HITS_REL_C="$(grep -cE 'stop reason = breakpoint 2\.[0-9]+' "$LLDB_LOG" || true)"
HITS_REL_H="$(grep -cE 'stop reason = breakpoint 3\.[0-9]+' "$LLDB_LOG" || true)"
echo "==> Breakpoint hits: TPipe_Content_create=$HITS_CREATE TPipe_Content_release=$HITS_REL_C TPipe_Handle_release=$HITS_REL_H"

# Cleanup the LLDB script unless the user asked to keep artifacts
if [ "${KEEP_BUILD:-0}" != "1" ]; then
    rm -f "$LLDB_SCRIPT"
    if [ "${KEEP_BUILD:-0}" != "1" ]; then
        # Also remove the test binary; the user can recompile with the
        # build scripts in this directory if they need it again.
        rm -f "$TEST_BIN"
    fi
fi

# Determine pass/fail. Two signals are equally valid:
#   1. The C program's own exit code (preferred; the test prints
#      'TPipe <name> test passed' on success and returns 0 from main
#      BEFORE the SubstrateVM teardown step).
#   2. The 'TPipe <name> test passed' string in the log — used as a
#      fallback because SubstrateVM's known safepoint abort during
#      graal_tear_down_isolate (documented in tpipe_abi_compliance.c)
#      can override the process exit code with a non-zero value
#      even when the C-level logic returned 0.
PASS_MARKER="${TEST_NAME//_test/} test passed"
case "$TEST_NAME" in
    tpipe_lifecycle_test)    PASS_MARKER="TPipe lifecycle test passed" ;;
    tpipe_handle_leak_test)  PASS_MARKER="TPipe handle leak test passed" ;;
    tpipe_concurrency_test)  PASS_MARKER="TPipe concurrency test passed" ;;
    *)                       PASS_MARKER="$TEST_NAME passed" ;;
esac

TEST_EXIT=""
if [ -n "$TEST_EXIT_LINE" ]; then
    TEST_EXIT="$(echo "$TEST_EXIT_LINE" | sed -E 's/.*status = ([^ ]+).*/\1/')"
fi
echo "==> C test exit code: ${TEST_EXIT:-<unknown>}"

if [ "$TEST_EXIT" = "0" ]; then
    echo "==> lldb_harness: PASS (exit 0)"
    exit 0
fi

# Non-zero exit — check whether the C test printed its own pass marker.
# If it did, the failure is a known SubstrateVM teardown issue, not a
# regression in the C ABI under test.
if grep -qF "$PASS_MARKER" "$LLDB_LOG"; then
    echo "==> lldb_harness: PASS (test printed '$PASS_MARKER' despite non-zero teardown exit)"
    exit 0
fi

echo "==> lldb_harness: FAIL (test exit=$TEST_EXIT, no pass marker in log)" >&2
exit 1
