package env

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Response from OpenRouter's /v1/chat/completions endpoint.
 * OpenAI-compatible response with OpenRouter-specific extensions.
 *
 * @see <a href="https://openrouter.ai/docs/api/api-reference/chat/send-chat-completion-request">Chat Completions API</a>
 *
 * @property id Unique identifier for this completion
 * @property objectType Object type (always "chat.completion") - NOTE: "object" is a Kotlin reserved keyword
 * @property created Unix timestamp of when the completion was created
 * @property model OpenRouter model ID used for this completion
 * @property choices List of completion choices
 * @property usage Token usage statistics
 * @property systemFingerprint System fingerprint for the response
 * @property serviceTier Service tier used for the request
 */
@Serializable
data class OpenRouterChatResponse(
    val id: String,
    @SerialName("object")
    val objectType: String = "chat.completion",
    val created: Long,
    val model: String,
    val choices: List<ChatChoice>,
    val usage: UsageInfo? = null,
    @SerialName("system_fingerprint")
    val systemFingerprint: String? = null,
    @SerialName("service_tier")
    val serviceTier: String? = null
)

/**
 * A single completion choice from the response.
 *
 * @property index Index of this choice in the choices array
 * @property message The message content generated by the model
 * @property finishReason The reason why generation stopped
 * @property logprobs Log probability information, if requested
 */
@Serializable
data class ChatChoice(
    val index: Int,
    val message: ChatMessage,
    @SerialName("finish_reason")
    val finishReason: String? = null,
    val logprobs: LogProbs? = null
)

/**
 * Token usage statistics for the completion request.
 *
 * @property promptTokens Number of tokens in the prompt
 * @property completionTokens Number of tokens in the completion
 * @property totalTokens Total tokens used
 * @property promptTokensDetails Detailed prompt token breakdown (if available)
 * @property completionTokensDetails Detailed completion token breakdown (if available)
 */
@Serializable
data class UsageInfo(
    @SerialName("prompt_tokens")
    val promptTokens: Int,
    @SerialName("completion_tokens")
    val completionTokens: Int,
    @SerialName("total_tokens")
    val totalTokens: Int,
    @SerialName("prompt_tokens_details")
    val promptTokensDetails: PromptTokensDetails? = null,
    @SerialName("completion_tokens_details")
    val completionTokensDetails: CompletionTokensDetails? = null
)

/**
 * Detailed breakdown of prompt tokens.
 *
 * @property cachedTokens Tokens from cached prompts
 */
@Serializable
data class PromptTokensDetails(
    @SerialName("cached_tokens")
    val cachedTokens: Int? = null
)

/**
 * Detailed breakdown of completion tokens.
 *
 * @property reasoningTokens Tokens used for reasoning (if applicable)
 * @property acceptedPredictionTokens Tokens in accepted predictions
 * @property rejectedPredictionTokens Tokens in rejected predictions
 */
@Serializable
data class CompletionTokensDetails(
    @SerialName("reasoning_tokens")
    val reasoningTokens: Int? = null,
    @SerialName("accepted_prediction_tokens")
    val acceptedPredictionTokens: Int? = null,
    @SerialName("rejected_prediction_tokens")
    val rejectedPredictionTokens: Int? = null
)

/**
 * Log probability information for the completion.
 *
 * @property tokenLogprobs Log probabilities for each token
 * @property tokens Tokens corresponding to the log probabilities
 * @property topLogprobs Top log probabilities at each token position
 */
@Serializable
data class LogProbs(
    @SerialName("token_logprobs")
    val tokenLogprobs: List<Double>? = null,
    val tokens: List<String>? = null,
    @SerialName("top_logprobs")
    val topLogprobs: List<TopLogProb>? = null
)

/**
 * Top log probability for a single token position.
 *
 * @property token The token string
 * @property logprob The log probability of the token
 * @property bytes Token bytes (if available)
 * @property topLogprob The log probability of the top alternative
 */
@Serializable
data class TopLogProb(
    val token: String,
    val logprob: Double,
    val bytes: List<Int>? = null,
    @SerialName("top_logprob")
    val topLogprob: Double? = null
)

/**
 * Streaming chunk for SSE responses.
 * Each chunk follows the format: data: {"id":"...","choices":[{"delta":{"content":"..."},"index":0}]}
 *
 * @property id Completion ID
 * @property objectType Object type (always "chat.completion.chunk")
 * @property created Unix timestamp
 * @property model Model ID used
 * @property choices List of delta choices
 */
@Serializable
data class StreamingChunk(
    val id: String,
    @SerialName("object")
    val objectType: String = "chat.completion.chunk",
    val created: Long,
    val model: String,
    val choices: List<StreamingChoice>
)

/**
 * A single streaming delta choice.
 *
 * @property index Index of this choice
 * @property delta The content delta
 * @property finishReason Reason for stopping (if applicable)
 */
@Serializable
data class StreamingChoice(
    val index: Int,
    val delta: DeltaMessage,
    @SerialName("finish_reason")
    val finishReason: String? = null
)

/**
 * A delta message for streaming responses.
 *
 * @property role Role of the message sender (if first chunk)
 * @property content Text content delta
 * @property reasoning Plain-text model reasoning delta (reasoning models
 * stream it ahead of visible content; see [ReasoningDetail])
 * @property reasoningDetails Structured reasoning delta entries (used by
 * providers that deliver reasoning as typed detail objects instead of a
 * plain string)
 */
@Serializable
data class DeltaMessage(
    val role: String? = null,
    val content: String? = null,
    val reasoning: String? = null,
    @SerialName("reasoning_details")
    val reasoningDetails: List<ReasoningDetail>? = null
)

/**
 * A single structured reasoning detail entry from a streaming delta.
 *
 * OpenRouter reasoning models deliver `choices[].delta.reasoning_details`
 * as a list of these objects. `text` carries full thinking content;
 * `summary` carries abbreviated reasoning; `signature` is provider
 * verification metadata. All fields are optional — entries may carry
 * any subset depending on the provider.
 *
 * @property type Reasoning detail type (e.g. "thinking", "summary")
 * @property text Full reasoning text for this detail entry
 * @property summary Abbreviated reasoning summary
 * @property id Provider-assigned detail identifier
 * @property format Content format identifier
 * @property index Position of this detail within the detail list
 * @property signature Provider verification signature
 */
@Serializable
data class ReasoningDetail(
    val type: String? = null,
    val text: String? = null,
    val summary: String? = null,
    val id: String? = null,
    val format: String? = null,
    val index: Int? = null,
    val signature: String? = null
)

/**
 * Error response from OpenRouter API.
 *
 * @property error Error details
 */
@Serializable
data class OpenRouterErrorResponse(
    val error: OpenRouterError
)

/**
 * OpenRouter error details.
 *
 * @property message Human-readable error message
 * @property code Error code (if available)
 * @property type Error type
 * @property codeBody Additional error code details (if available)
 */
@Serializable
data class OpenRouterError(
    val message: String,
    val code: String? = null,
    val type: String? = null,
    @SerialName("code_body")
    val codeBody: String? = null,
    val url: String? = null,
    val param: String? = null,
    val provider: String? = null
)