package env

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents a single message in a conversation for Ollama's chat API.
 *
 * @property role The role of the message sender (system, user, assistant, or tool).
 * @property content The text content of the message.
 * @property images Optional list of base64-encoded images for multimodal models.
 * @property toolCalls Optional list of tool calls generated by the model.
 */
@Serializable
data class OllamaMessage(
    val role: String,
    val content: String,
    val images: List<String>? = null,
    @SerialName("tool_calls")
    val toolCalls: List<OllamaToolCall>? = null
)

/**
 * Represents a tool call generated by the model.
 * @property function The function details of the tool call.
 */
@Serializable
data class OllamaToolCall(
    val function: OllamaFunctionCall
)

/**
 * Represents the function details of a tool call.
 * @property name The name of the function to call.
 * @property arguments The arguments for the function call.
 */
@Serializable
data class OllamaFunctionCall(
    val name: String,
    val arguments: kotlinx.serialization.json.JsonObject
)
