package com.TTT.TraceServer.auth

/**
 * Strategy interface for hashing dashboard passwords. The default v2
 * implementation is [Pbkdf2PasswordHasher], which uses the JDK's
 * `SecretKeyFactory("PBKDF2WithHmacSHA256")` so the surface stays native-safe
 * (no BouncyCastle, no JNI).
 *
 * Implementations are expected to be pure functions: same input + same salt
 * yields the same [HashedPassword]. The salt is generated by the caller (or
 * by [Pbkdf2PasswordHasher] when none is supplied) so the [verify] path can
 * use a constant-time comparison.
 */
interface PasswordHasher {

    /**
     * Hashes [plaintext]. When [salt] is `null` a fresh cryptographically
     * random salt is generated. The returned [HashedPassword] is portable:
     * the [HashedPassword.algorithm] string is the canonical Java algorithm
     * name recognized by `SecretKeyFactory.getInstance`.
     *
     * @param plaintext the cleartext password supplied by the user.
     * @param salt optional pre-generated salt; `null` triggers random
     *  generation. Pass an explicit value when re-hashing a known salt
     *  (e.g. for verification or admin rotation).
     */
    fun hash(plaintext: String, salt: ByteArray? = null): HashedPassword

    /**
     * Verifies a candidate [plaintext] against a stored [expected] hash in
     * constant time. Returns `true` when the derived bytes match.
     */
    fun verify(plaintext: String, expected: HashedPassword): Boolean

    /**
     * Default iteration count. Aligned with OWASP 2025 guidance for
     * PBKDF2-HMAC-SHA256; tunable via the constructor of the
     * concrete implementation.
     */
    val defaultIterations: Int get() = 600_000
}
